Repository antopilo/Nuake, pull requests merged in 2023-07, with the labels that each got.

#12 File browser doesn't display 1st element
  Editor/src/Windows/FileSystemUI.cpp
Labels: bug

#13 Added Play Mode shortcut (F5)
  Editor/src/Windows/EditorInterface.cpp
Labels: enhancement

#14 Creating New Project doesn't add .project
  Editor/src/Windows/EditorInterface.cpp
  Editor/src/Windows/WelcomeWindow.cpp
  Nuake/src/Resource/Project.cpp
  Nuake/src/Resource/Project.h
Labels: bug, enhancement

#15 Creating New Project Editor does not create directory
  Editor/src/Windows/EditorInterface.cpp
Labels: enhancement

#16 File Browser - Add Wren Script on Right-Click
  Editor/src/Windows/FileSystemUI.cpp
Labels: enhancement

#17 Refresh File Browser on Fìle Creation
  Editor/src/Windows/FileSystemUI.cpp
  Editor/src/Windows/FileSystemUI.h
Labels: enhancement

#18 Feature/NK-76 Redesign welcome screen
  Editor/src/Windows/WelcomeWindow.cpp
  Editor/src/Windows/WelcomeWindow.h
Labels: enhancement

#20 Delete Hovered File from Context Menu
  Editor/src/Windows/FileSystemUI.cpp
  Editor/src/Windows/FileSystemUI.h
  Nuake/src/Core/FileSystem.cpp
  Nuake/src/Core/FileSystem.h
Labels: enhancement

#26 NK-99 - Show Folder in File Explorer
  Editor/Editor.cpp
  Editor/src/NewEditor.cpp
  Editor/src/Windows/EditorInterface.cpp
  Editor/src/Windows/FileSystemUI.cpp
  Editor/src/Windows/WelcomeWindow.cpp
  Nuake/Engine.cpp
  Nuake/src/Core/FileSystem.cpp
  Nuake/src/Core/FileSystem.h
  Nuake/src/Core/OS.cpp
  Nuake/src/Core/OS.h
Labels: enhancement

#29 NK-78 - Display wren script in properties
  Editor/src/Windows/EditorSelectionPanel.cpp
  Editor/src/Windows/EditorSelectionPanel.h
  Nuake/src/Scripting/WrenScript.cpp
  Nuake/src/Scripting/WrenScript.h
Labels: enhancement

#30 NK-108 - Removed delete from .project context menu
  Editor/src/Windows/FileSystemUI.cpp
Labels: enhancement

#31 NK-110 - 'Open...' button
  Editor/src/Windows/EditorSelectionPanel.cpp
  Editor/src/Windows/FileSystemUI.cpp
  Nuake/src/Core/OS.cpp
  Nuake/src/Core/OS.h
Labels: enhancement

#34 NK-113 - Open Wren Script File with Double Click
  Editor/src/ComponentsPanel/ScriptPanel.h
  Nuake/src/Scene/Components/WrenScriptComponent.h
Labels: enhancement

#37 NK-126 - Click Empty Component Script
  Editor/src/ComponentsPanel/ScriptPanel.cpp
  Editor/src/ComponentsPanel/ScriptPanel.h
  Editor/src/Windows/EditorInterface.cpp
  Editor/src/Windows/EditorSelectionPanel.cpp
  Editor/src/Windows/FileSystemUI.cpp
  Editor/src/Windows/FileSystemUI.h
  Nuake/src/Core/FileSystem.cpp
Labels: enhancement

#38 Feature/nk 102 generic confirmation popup
  Editor/src/Misc/PopupHelper.cpp
  Editor/src/Misc/PopupHelper.h
Labels: enhancement

#39 NK-74 - Double click to open scene
  Editor/src/Windows/FileSystemUI.cpp
Labels: enhancement

#40 Rework logger
  Editor/Editor.cpp
  Editor/src/NewEditor.cpp
  Editor/src/Windows/EditorInterface.cpp
  Editor/src/Windows/FileSystemUI.cpp
  Editor/src/Windows/WelcomeWindow.cpp
  Nuake/Engine.cpp
  Nuake/src/Core/Logger.cpp
  Nuake/src/Core/Logger.h
  Nuake/src/Core/Physics/PhysicsManager.cpp
  Nuake/src/Rendering/Mesh/Mesh.cpp
  Nuake/src/Rendering/Shaders/ShaderManager.cpp
  Nuake/src/Rendering/Textures/MaterialManager.cpp
  Nuake/src/Rendering/Textures/Texture.cpp
  Nuake/src/Rendering/Vertex.h
  Nuake/src/Resource/ModelLoader.cpp
  Nuake/src/Resource/Project.cpp
  Nuake/src/Resource/ResourceLoader.h
  Nuake/src/Scene/Scene.cpp
  Nuake/src/Scene/Systems/PhysicsSystem.cpp
  Nuake/src/Scripting/Modules/SceneModule.h
  Nuake/src/Scripting/ScriptingEngine.cpp
  Nuake/src/UI/Font/FontLoader.h
  Nuake/src/UI/Font/FontManager.cpp
  Nuake/src/UI/InterfaceParser.cpp
  Nuake/src/UI/UserInterface.cpp
  Nuake/src/Window.cpp
Labels: enhancement

#41 NK-114 - Creating Prefab without extension doesn't add .prefab
  Editor/src/Windows/EditorInterface.cpp
  Editor/src/Windows/FileSystemUI.cpp
Labels: enhancement

#42 NK-111 Copy Menu in Context Menu
  Editor/src/Windows/FileSystemUI.cpp
  Nuake/src/Core/OS.cpp
  Nuake/src/Core/OS.h
Labels: enhancement

#44 NK-136 - Rework Context menu
  Editor/src/Windows/FileSystemUI.cpp
  Nuake/src/Resource/Project.cpp
Labels: enhancement

#46 NK-107 Context menu folder
  Editor/src/Windows/FileSystemUI.cpp
  Editor/src/Windows/FileSystemUI.h
  Nuake/src/Core/FileSystem.cpp
  Nuake/src/Core/FileSystem.h
Labels: enhancement

#48 NK-141 Rename File/Folder
  Editor/src/Misc/PopupHelper.cpp
  Editor/src/Misc/PopupHelper.h
  Editor/src/Windows/FileSystemUI.cpp
  Nuake/src/Core/OS.cpp
  Nuake/src/Core/OS.h
Labels: enhancement

#50 NK-143 - Delete Confirmation Popup
  Editor/src/Windows/FileSystemUI.cpp
Labels: enhancement

#51 NK-79 - Rename File & Folder
  Editor/src/Misc/PopupHelper.cpp
Labels: bug

#53 NK-70 - Add menu bar shortcuts
  Editor/src/Windows/EditorInterface.cpp
Labels: enhancement
